---
resources:
- name: chaos-lemur
  type: git
  source:
    uri: https://github.com/Kevin-Fries-Altoros/chaos-lemur.git

- name: pcf-app
  type: cf
  source:
    api: {{pcf-url}}
    username: {{pcf-username}}
    password: {{pcf-password}}
    organization: {{pcf-organization}}
    space: {{pcf-space}}
    skip_cert_check: True

jobs:
- name: deploy-app
  plan:
    - get: chaos-lemur
      trigger: true
    - task: build-binary
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8-jdk-alpine

      inputs:
        - name: chaos-lemur

      outputs:
        - name: chaos-lemur-deploy

      run:
        path: chaos-lemur/ci/package.sh

    - put: pcf-app
      inputs:
        - name: chaos-lemur-deploy
      params:
        manifest: chaos-lemur-deploy/manifest.yml
